services:
  postgres:
    image: postgres:18.4
    container_name: campuseats-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: campuseats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - campuseats_postgres_data:/var/lib/postgresql

volumes:
  campuseats_postgres_data: